stages:
  - build

build-alpine-container:
  tags:
    - docker-shell
  environment:
    name: build-and-push-alpine-container
  stage: build

  before_script:
    - docker info
    - id

  script:
    - mkdir -p /home/gitlab-runner/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /home/gitlab-runner/.docker/config.json
    - docker build . -f docker/alpine/Dockerfile -t $CI_REGISTRY_IMAGE:alpine-$CI_COMMIT_TAG --build-arg GIT_DOMAIN=$CI_SERVER_HOST --build-arg GIT_USERNAME=$CI_REGISTRY_USER --build-arg GIT_PASSWORD=$CI_REGISTRY_PASSWORD
    - docker push $CI_REGISTRY_IMAGE:alpine-$CI_COMMIT_TAG
  only:
    - tags

build-slim-container:
  tags:
    - docker-shell
  environment:
    name: build-and-push-slim-container
  stage: build
  script:
    - mkdir -p /home/gitlab-runner/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /home/gitlab-runner/.docker/config.json
    - docker build . -f docker/slim/Dockerfile -t $CI_REGISTRY_IMAGE:slim-$CI_COMMIT_TAG --build-arg GIT_DOMAIN=$CI_SERVER_HOST --build-arg GIT_USERNAME=$CI_REGISTRY_USER --build-arg GIT_PASSWORD=$CI_REGISTRY_PASSWORD
    - docker push $CI_REGISTRY_IMAGE:slim-$CI_COMMIT_TAG
  only:
    - tags
